### ISSUE TITLE
stevetemplates::beamer producing table of contents at the end of document

### ISSUE THREAD

**Issue by WihanZA** [svmiller/stevetemplates#10]
Hi! Thanks for your wonderful templates package. I'm a newcomer to the package and currently working from a R Markdown document initiated from the template. A table of contents is appearing at the end of my document. `toc = FALSE` in the YAML under `stevetemplates::beamer:` does not seem to work, nor am I sure how to move it at all. I can overcome the issue when I knit the `.Rmd` file and remove the toc at the end of the corresponding `tex` document , and compile a pdf from there. Thanks in advance, I'm really loving the templates so far. Regards

**Comment by almartin82** [comment]
I can reproduce this using the [skeleton](https://github.com/svmiller/stevetemplates/blob/master/inst/rmarkdown/templates/beamer/skeleton/skeleton.Rmd) document.

I believe that this is because the template has a hand-coded table of contents [section](https://github.com/svmiller/stevetemplates/blob/b6a3904822874a1653abd2a2c1b27cac0c86b476/inst/rmarkdown/templates/beamer/resources/template.tex#L425) that is not controlled by the [toc](https://github.com/svmiller/stevetemplates/blob/master/inst/rmarkdown/templates/beamer/resources/template.tex#L391) logic.

**Comment by almartin82** [comment]
@WihanZA I forked the project and opened a PR that removes the hardcoded TOC - you can install using `devtools::install_github("almartin82/stevetemplates")` if you'd like

**Comment by svmiller** [comment]
For what it's worth, this a deliberate design feature. I like this trailing table of contents because it better facilitates an ability to jump back to assorted sections of a presentation. It's also a better signal of "presentation is over" than just ending on the conclusion section. It ultimately works for my purposes.

That said, the development version of the package now has a `no_toc_after:` field in the YAML that can [disable this trailing table of contents](https://github.com/svmiller/stevetemplates/blob/master/inst/rmarkdown/templates/beamer/resources/template.tex#L425). Just specify it in the YAML to be `TRUE`.

**Comment by WihanZA** [comment]
Excellent! Thanks @almartin82. @svmiller the trailing toc is sensible for the reasons you provide. Thanks for the new feature.

**Comment by almartin82** [comment]
Love it!  Great outcome 👍
