### ISSUE TITLE
amsmath in article tempate

### ISSUE THREAD

**Issue by ashenkin** [svmiller/stevetemplates#3]
Hi Steve,
Wondering if there's a particular reason you've omitted amsmath from the article template?  If not, would you consider adding `\usepackage{amssymb,amsmath}` to it?
Thanks...

**Comment by svmiller** [comment]
The particular reason here is this template (`stevetemplates::article`) was originally an old LaTeX template of mine (and not a Pandoc template). In my field, we don't typically use a lot of mathematical notation so I didn't include it. Incidentally, the other article template here (`stevetemplates::article2`) does have this and should have all the same goodies in the other article template.

I'll go ahead and include that though since it's not going to break anything elsewhere in the template.

**Comment by svmiller** [comment]
[Updated now](https://github.com/svmiller/stevetemplates/commit/136cd9ac8470b306a3e35e228ba9989df05dcba5#diff-c0f594291bd9345c28f0053f4c4a934ce170977d8b29e26dcd432010fb7d0b8a). Should be good to go.
